version: '3.4'

services:
  # If you run multiple nodes on the same instance, you can copy/paste the 
  # entire entry below(lines 8-20) and change 
  # the service name below as, for example
  #keep-ops-toolkit-data-backups-ecdsa:
  keep-ops-toolkit-data-backups:
    image: keep-ops-toolkit-data-backups
    container_name: data-backups-rb
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: /app/bin/docker-cron.sh
    user: "appuser"
    logging:
      # below is the config as per mutedtommy's https://medium.com/@hr12rtk/keep-random-beacon-node-monitoring-grafana-prometheus-and-loki-4a4b669b31ea
      # If you don't have/want to use loki, use the default `driver: json-file`
      driver: loki
      options:
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
    volumes:
      - ./init-vars.sh:/app/cfg/init-vars.sh
      - ./rclone.conf:/home/appuser/.config/rclone/rclone.conf
      # Load up your main folder or individual folders here, examples below
      # - /home/ubuntu/keep-ecdsa:/home/appuser/keep-backups
      # - /mnt/secure-volume/persistence:/home/appuser/keep-backups/persistence
      - ./sample-data:/home/appuser/keep-backups:ro
      # note the :ro at the end to make the mount read-only
